on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Lost Pixel

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm -g install jest
          npx playwright install

      - name: Lint
        run: npm run lint

      - name: Build Example Storybook v6.4
        run: npm run build-example-storybook-v6.4

      - name: Build Example Storybook v6.5 with StoryStore v7
        run: npm run build-example-storybook-v6.5-storystore-v7

      - name: Build Example Pages
        run: npm run build-example-next-js-pages

      - name: Build Example Ladle
        run: npm run build-example-ladle

      - name: Build Example Histoire
        run: npm run build-example-histoire

      - name: Build Example Vite
        run: npm run build-example-vite

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Run Example Next.js Pages
        run: npm run run-example-next-js-pages &

      - name: Run Example Vite
        run: npm run run-example-vite &

      - name: Test on examples
        run: npm run test-on-examples

      - name: Artifacts upload
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: shots
          path: examples/**/.lostpixel
