name: PR Docker Build

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm -g install jest
          npx playwright install

      - name: Lint
        run: npm run lint

      - name: Build Example Storybook v6.4
        run: npm run build-example-storybook-v6.4

      - name: Build Example Storybook v6.5 with StoryStore v7
        run: npm run build-example-storybook-v6.5-storystore-v7

      - name: Test
        run: npm run test

      - name: Set Docker tag
        run: echo DOCKER_TAG=$(echo pr-${GITHUB_SHA:0:8}) >> $GITHUB_ENV

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@a0b8f0e2d777562c13523b9a4d9480bae383486b
        env:
          RELEASE_VERSION: '${{ env.DOCKER_TAG }}'
        with:
          name: lostpixel/lost-pixel-pr-build
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: '${{ env.DOCKER_TAG }}'
          buildoptions: '--compress --force-rm'

      - name: Slack Notification
        uses: 8398a7/action-slack@a74b761b4089b5d730d813fbedcd2ec5d394f3af
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }}\n\nlostpixel/lost-pixel-pr-build:${process.env.DOCKER_TAG}`
              }]
            }
