name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci
          npm -g install jest
          npx playwright install

      - name: Lint
        run: npm run lint

      - name: Build Example Storybook v6.4
        run: npm run build-example-storybook-v6.4

      - name: Build Example Storybook v6.5 with StoryStore v7
        run: npm run build-example-storybook-v6.5-storystore-v7

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Create .npmrc
        run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to npm
        run: npm publish --access public

      - name: Slack Notification
        uses: 8398a7/action-slack@a74b761b4089b5d730d813fbedcd2ec5d394f3af
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}\n\n- ${{join(github.event.commits.*.message, '\n- ')}}\n\n`,
                fields: [
                  {
                    title: 'NPM Release',
                    value: process.env.GITHUB_REF,
                    short: true
                  },
                  {
                    title: 'Repo',
                    value: process.env.AS_REPO,
                    short: true
                  }
                ]
              }]
            }

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@43dc228e327224b2eda11c8883232afd5b34943b
        with:
          name: lostpixel/lost-pixel
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 'latest,${{ github.event.release.tag_name }}'
          buildoptions: '--compress --force-rm'
          platforms: linux/amd64,linux/arm64

      - name: Slack Notification
        uses: 8398a7/action-slack@a74b761b4089b5d730d813fbedcd2ec5d394f3af
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `${process.env.AS_WORKFLOW}\n${process.env.AS_JOB} (${process.env.AS_COMMIT}) of ${process.env.AS_REPO}@${process.env.AS_REF} by ${process.env.AS_AUTHOR} ${{ job.status }} in ${process.env.AS_TOOK}\n\n- ${{join(github.event.commits.*.message, '\n- ')}}\n\n`,
                fields: [
                  {
                    title: 'Docker tag',
                    value: process.env.RELEASE_VERSION,
                    short: true
                  },
                  {
                    title: 'Repo',
                    value: process.env.AS_REPO,
                    short: true
                  }
                ]
              }]
            }
